version: "3.8"

services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - ./data/primary:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=POSTGRES_PASSWORD_SET
      - POSTGRESQL_USERNAME=otheruser
      - POSTGRESQL_PASSWORD=psqlotherpassword
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
    networks:
      - bridge

  pg-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - ./data/replica1:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=POSTGRES_PASSWORD_SET
      - POSTGRESQL_USERNAME=otheruser
      - POSTGRESQL_PASSWORD=psqlotherpassword
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
    networks:
      - bridge

  pgpool:
    image: bitnami/pgpool:4
    depends_on:
      pg-0:
        condition: service_healthy
      pg-1:
        condition: service_healthy
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432:4:primary:ALWAYS_PRIMARY,1:pg-1:5432:6:replica
      - PGPOOL_BACKEND_APPLICATION_NAMES=pg-0,pg-1
      - PGPOOL_SR_CHECK_USER=otheruser
      - PGPOOL_SR_CHECK_PASSWORD=psqlotherpassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=POSTGRES_PASSWORD_SET
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=POSTGRES_PASSWORD_SET
      - PGPOOL_AUTO_FAILBACK=yes
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_STATEMENT_LOAD_BALANCING=yes
      - PGPOOL_NUM_INIT_CHILDREN=10
      - PGPOOL_MAX_POOL=4
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
