version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/dev:/var/lib/postgresql/data
    networks:
      - bridge

  phppgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - bridge

networks:
  bridge:
    driver: bridge