version: "3"

services:
  pg-1:
    image: bitnami/postgresql-repmgr:14
    hostname: pg-1
    ports:
      - 5432
    volumes:
      - ./data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=POSTGRES_PASSWORD_SET
      - POSTGRESQL_USERNAME=otheruser
      - POSTGRESQL_PASSWORD=psqlotherpassword
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
